import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import LivePreview from "@/components/LivePreview";
import {draftMode} from "next/headers";
import Layout from "@/layouts/default";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
        <Layout>
            {children}
            <LivePreview/>
        </Layout>
        </body>
        </html>
    );
}
